[workspace]
resolver = "2"
members = [
    "bin/agc",
    "bin/aglsp",
    "bin/agsm",
]


[profile.profiling]
inherits = "release"
debug = true

[workspace.lints.clippy]
disallowed_types = "deny"
large_enum_variant = "deny"

[patch."https://github.com/CierCier/elise.git"]
elise-core = { path = "../elise/crates/elise-core" }
elise-lex = { path = "../elise/crates/elise-lex" }
elise-parse = { path = "../elise/crates/elise-parse" }
