#!/usr/bin/env python3
"""
Generate typed Silver syscall wrappers from Linux kernel headers.

Usage:
    python3 scripts/gen-syscall-wrappers.py <unistd_64.h> <arg_counts.json> [output.ag]

Given a kernel `unistd_64.h` header and a JSON mapping of syscall name to argument count,
generates a Silver source file with typed wrappers for every syscall.

If output path omitted, writes to stdout.
"""

import json
import re
import sys
from datetime import date


def parse_kernel_header(path: str) -> dict[str, int]:
    """Parse unistd_64.h and return syscall_name -> syscall_number."""
    syscalls: dict[str, int] = {}
    with open(path) as f:
        for line in f:
            m = re.match(r"#define\s+__NR_(\w+)\s+(\d+)", line)
            if m:
                syscalls[m.group(1)] = int(m.group(2))
    return syscalls


def generate_wrappers(
    syscalls: dict[str, int],
    arg_counts: dict[str, int | None],
) -> str:
    lines = []
    lines.append("// Auto-generated by scripts/gen-syscall-wrappers.py")
    lines.append(
        f"// Source: Linux x86_64 syscall table ({len(syscalls)} syscalls)"
    )
    lines.append(f"// Generated: {date.today().isoformat()}")
    lines.append("// DO NOT EDIT -- regenerate with:")
    lines.append("//   python3 scripts/gen-syscall-wrappers.py \\")
    lines.append("//       <path/to/unistd_64.h> \\")
    lines.append("//       std/sys/syscall_args.json \\")
    lines.append("//       > std/sys/linux.ag")
    lines.append("")
    lines.append("import std.sys.syscall;")
    lines.append("")

    names = sorted(syscalls.keys(), key=lambda n: syscalls[n])

    for name in names:
        number = syscalls[name]
        arg_count = arg_counts.get(name)

        if arg_count is None:
            n = 6
            args = [f"a{i}" for i in range(1, n + 1)]
            params = ", ".join(f"i64 a{i}" for i in range(1, n + 1))
            call_args = ", ".join([str(number)] + args)
            comment = "  // arg count guessed"
        else:
            n = arg_count
            if n > 0:
                params = ", ".join(f"i64 a{i}" for i in range(1, n + 1))
                call_args = ", ".join([str(number)] + [f"a{i}" for i in range(1, n + 1)])
            else:
                params = ""
                call_args = str(number)
            comment = ""

        wrapper_name = f"sys_{name}"
        lines.append(f"pub i64 {wrapper_name}({params}) {{")
        lines.append(f"    return syscall{n}({call_args});{comment}")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def main():
    if len(sys.argv) < 3:
        print(__doc__, file=sys.stderr)
        sys.exit(1)

    header_path = sys.argv[1]
    arg_count_path = sys.argv[2]
    output_path = sys.argv[3] if len(sys.argv) > 3 else None

    syscalls = parse_kernel_header(header_path)
    if not syscalls:
        print(f"Error: no syscalls found in {header_path}", file=sys.stderr)
        sys.exit(1)

    with open(arg_count_path) as f:
        arg_counts = json.load(f)

    missing = set(syscalls.keys()) - set(arg_counts.keys())
    if missing:
        print(
            f"Warning: {len(missing)} syscalls missing from arg count JSON: "
            f"{', '.join(sorted(missing)[:10])}...",
            file=sys.stderr,
        )

    source = generate_wrappers(syscalls, arg_counts)

    if output_path:
        with open(output_path, "w") as f:
            f.write(source)
        print(f"Generated {len(syscalls)} wrappers -> {output_path}", file=sys.stderr)
    else:
        sys.stdout.write(source)


if __name__ == "__main__":
    main()
