#!/usr/bin/env python3
"""STD-004: differential fuzz for Silver ftoa vs Rust `{}` Display.

Generates a deterministic corpus of f64 bit patterns (seeded), formats each
with the stage0-built Silver program (std/fmt.ag `ftoa`) and with a rustc
reference (`println!("{}", f64::from_bits)`), and requires byte-identical
output per line. Catches Grisu2-vs-Grisu3 divergences that would otherwise
break every float-bearing diagnostic/.agm diff (plan risk #5).
"""

from __future__ import annotations

import argparse
import pathlib
import random
import struct
import subprocess
import tempfile

SEED = 0xC0FFEE


def bits_of(v: float) -> int:
    return struct.unpack("<Q", struct.pack("<d", v))[0]


def directed() -> list[int]:
    out = [
        0x0000000000000000,  # +0
        0x8000000000000000,  # -0
        0x7FF0000000000000,  # +inf
        0xFFF0000000000000,  # -inf
        0x7FF8000000000000,  # qNaN
        0xFFF8000000000000,  # -qNaN (Rust still prints NaN)
        0x7FF0000000000001,  # sNaN payload
        0x7FFFFFFFFFFFFFFF,  # NaN max payload
        0x0000000000000001,  # min subnormal (5e-324)
        0x000FFFFFFFFFFFFF,  # max subnormal
        0x0010000000000000,  # min normal
        0x7FEFFFFFFFFFFFFF,  # max finite
        0x3FF0000000000000,  # 1.0
    ]
    for v in (0.1, 0.2, 0.3, 1.0 / 3.0, 2.0 / 3.0, 1e21, 1e22, 1e23,
              1e100, 1e-100, 1e300, 1e-300, 123456789.123456789,
              9007199254740991.0, 9007199254740992.0, 9007199254740994.0,
              3.141592653589793, 2.718281828459045, 100.0, 0.5, 1.5,
              123456789012345678.0, 1e15, 1e16, 1e17, 0.000001, 123.456e-10):
        out.append(bits_of(v))
    return out


def random_corpus(rng: random.Random, n_uniform: int, n_exp: int,
                  n_near_one: int, n_tiny: int) -> list[int]:
    out = [rng.getrandbits(64) for _ in range(n_uniform)]
    for _ in range(n_exp):
        exp = rng.randrange(1, 2046)
        mant = rng.getrandbits(52)
        sign = rng.getrandbits(1)
        out.append((sign << 63) | (exp << 52) | mant)
    one = bits_of(1.0)
    for _ in range(n_near_one):
        out.append((one + rng.randrange(-1000, 1000)) & 0xFFFFFFFFFFFFFFFF)
    for _ in range(n_tiny):
        out.append(rng.randrange(1, 1 << 53))
    return out


SILVER_PROG = """\
// Generated by check_float_format.py — do not edit.
import std.fmt;
import std.io;
import std.io.file;
import std.mem.vec;
import std.result;
import std.string;

u64 parse_hex(str line) {
    u64 acc = (u64)0;
    i64 i = 0;
    i64 len = strlen(line);
    while (i < len) {
        u8 ch = line[i];
        u64 digit = (u64)0;
        if (ch >= (u8)'0' && ch <= (u8)'9') {
            digit = (u64)(ch - (u8)'0');
        } else if (ch >= (u8)'a' && ch <= (u8)'f') {
            digit = (u64)(ch - (u8)'a') + (u64)10;
        } else if (ch >= (u8)'A' && ch <= (u8)'F') {
            digit = (u64)(ch - (u8)'A') + (u64)10;
        } else {
            i += 1;
            continue;
        }
        acc = acc * (u64)16 + digit;
        i += 1;
    }
    return acc;
}

i32 main() {
    Result<String, Error> loaded = String.from_file("PATTERNS_PATH");
    if (loaded.is_err()) {
        return 1;
    }
    String text = loaded.unwrap();
    SplitIter lines = text.split("\\n");
    u8 buf[344];
    while (true) {
        Optional<str> item = lines.next();
        if (item.is_none()) { break; }
        str line = item.unwrap();
        if (strlen(line) == 0) { continue; }
        u64 bits = parse_hex(line);
        f64* fp = (f64*)&bits;
        f64 v = *fp;
        i64 n = ftoa(v, (u8*)&buf[0]);
        String out = String.new();
        out.push_bytes((u8*)&buf[0], n);
        out.push((u8)10);
        STDOUT.write_str(out.to_str());
    }
    return 0;
}
"""

RUST_PROG = """\
use std::io::BufRead;
fn main() {
    let f = std::fs::File::open("PATTERNS_PATH").unwrap();
    for line in std::io::BufReader::new(f).lines() {
        let line = line.unwrap();
        let line = line.trim();
        if (line.is_empty()) { continue; }
        let bits = u64::from_str_radix(line.trim_start_matches("0x"), 16).unwrap();
        println!("{}", f64::from_bits(bits));
    }
}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--stage0", required=True, type=pathlib.Path)
    parser.add_argument("--count", type=int, default=400,
                        help="random patterns on top of directed ones")
    args = parser.parse_args()
    stage0 = args.stage0.resolve()

    rng = random.Random(SEED)
    n = args.count
    patterns = directed() + random_corpus(
        rng, n_uniform=n // 2, n_exp=n // 4,
        n_near_one=n // 8, n_tiny=n - n // 2 - n // 4 - n // 8)

    with tempfile.TemporaryDirectory(prefix="silver-float-fuzz-") as tmp:
        root = pathlib.Path(tmp)
        (root / "patterns.txt").write_text(
            "".join(f"{p:016x}\n" for p in patterns))
        silver_src = SILVER_PROG.replace("PATTERNS_PATH",
                                         str(root / "patterns.txt"))
        (root / "fuzz.ag").write_text(silver_src)
        (root / "ref.rs").write_text(RUST_PROG.replace(
            "PATTERNS_PATH", str(root / "patterns.txt")))

        silver_bin = root / "fuzz_silver"
        build = subprocess.run(
            [str(stage0), "build", str(root / "fuzz.ag"),
             "--no-cache", "-o", str(silver_bin)],
            text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            check=False)
        if build.returncode != 0:
            raise AssertionError(
                f"fuzz program build failed:\n{build.stderr}")
        ref_bin = root / "fuzz_ref"
        refc = subprocess.run(
            ["rustc", "-O", str(root / "ref.rs"), "-o", str(ref_bin)],
            text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            check=False)
        if refc.returncode != 0:
            raise AssertionError(f"rustc failed:\n{refc.stderr}")

        silver = subprocess.run([str(silver_bin)], text=True,
                                stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                                check=False)
        ref = subprocess.run([str(ref_bin)], text=True,
                             stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                             check=False)
        if silver.returncode != 0:
            raise AssertionError(
                f"silver fuzz binary rc={silver.returncode}\n{silver.stderr}")
        silver_lines = silver.stdout.splitlines()
        ref_lines = ref.stdout.splitlines()
        if len(silver_lines) != len(patterns):
            raise AssertionError(
                f"silver emitted {len(silver_lines)} lines, "
                f"expected {len(patterns)}")
        if len(ref_lines) != len(patterns):
            raise AssertionError(
                f"reference emitted {len(ref_lines)} lines, "
                f"expected {len(patterns)}")

        mismatches: list[str] = []
        for i, (bits, got, want) in enumerate(
                zip(patterns, silver_lines, ref_lines)):
            if got != want:
                mismatches.append(f"  [{i}] bits=0x{bits:016x} "
                                  f"silver={got!r} rust={want!r}")
        print(f"float-format fuzz: {len(patterns)} patterns "
              f"({len(patterns) - len(directed())} random, seed={SEED:#x}), "
              f"{len(mismatches)} mismatches")
        for m in mismatches[:20]:
            print(m)
        return 1 if mismatches else 0


if __name__ == "__main__":
    raise SystemExit(main())